/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 *
 * Created on 25 Jan, 2019, 12:31:00 AM
 */

package Student;

import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author chaudhary
 */
public class NewJFrame extends javax.swing.JFrame {
int attempts=1;
DatabaseConnection cobj;
Statement stmt;
ResultSet rst;

    /** Creates new form NewJFrame */
    public NewJFrame() {
        initComponents();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pssword = new javax.swing.JLabel();
        passtf = new javax.swing.JPasswordField();
        usertf = new javax.swing.JTextField();
        loginjButton1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        username = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(java.awt.Color.white);

        pssword.setFont(new java.awt.Font("Tahoma", 1, 18));
        pssword.setForeground(new java.awt.Color(255, 255, 255));
        pssword.setIcon(new javax.swing.ImageIcon("G:\\College Club Report\\College Club Report\\collegeclub\\build\\classes\\collegeclub\\resources\\Apps-preferences-desktop-user-password-icon.png")); // NOI18N
        pssword.setText("PASSWORD:");

        passtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passtfActionPerformed(evt);
            }
        });

        loginjButton1.setFont(new java.awt.Font("Tahoma", 1, 18));
        loginjButton1.setIcon(new javax.swing.ImageIcon("G:\\College Club Report\\College Club Report\\collegeclub\\build\\classes\\collegeclub\\resources\\sign-check-icon (1).png")); // NOI18N
        loginjButton1.setText("Login");
        loginjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginjButton1ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18));
        jButton1.setIcon(new javax.swing.ImageIcon("G:\\College Club Report\\College Club Report\\collegeclub\\build\\classes\\collegeclub\\resources\\reset.png")); // NOI18N
        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        username.setFont(new java.awt.Font("Tahoma", 1, 18));
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setIcon(new javax.swing.ImageIcon("G:\\College Club Report\\College Club Report\\collegeclub\\build\\classes\\collegeclub\\resources\\USERNAME.PNG")); // NOI18N
        username.setText("USERNAME:");

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("G:\\College Club Report\\College Club Report\\collegeclub\\build\\classes\\collegeclub\\resources\\man-icon (1).png")); // NOI18N
        jLabel1.setText("LOGIN");
        jLabel1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pssword)
                    .addComponent(username))
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(loginjButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(passtf)
                    .addComponent(usertf, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 849, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(usertf, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pssword, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passtf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(174, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passtfActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_passtfActionPerformed

    private void loginjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginjButton1ActionPerformed
        if(usertf.getText().equals("admin")&&passtf.getText().equals("admin")){
            JOptionPane.showMessageDialog(null,"LOGIN SUCCESSFUL");
            
            
            setVisible(false);

            AddStudent obj=new AddStudent();
           obj.setVisible(true);

        }

        else if ( attempts==3&&usertf.getText()!="admin"&&passtf.getText()!="admin" ){


            JOptionPane.showMessageDialog(null, "number of attempts exceeded"+attempts);
            JOptionPane.showMessageDialog(null,"LOGIN UNSUCCESSFULL");
            System.exit(0);
        }else{
            JOptionPane.showMessageDialog(null,"Number of attempts " +attempts);
            attempts++;
            usertf.setText("");
            passtf.setText("");
        }
}//GEN-LAST:event_loginjButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        usertf.setText("");
        passtf.setText("");
}//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton loginjButton1;
    private javax.swing.JPasswordField passtf;
    private javax.swing.JLabel pssword;
    private javax.swing.JLabel username;
    private javax.swing.JTextField usertf;
    // End of variables declaration//GEN-END:variables

}
